flex
OlegGluhov/DZ2024 pull request #3
Opened 2024-02-19 12:08 UTC by OlegGluhov

2024-02-19 12:12 UTC, OlegGluhov commented
Форму немножко попытался сделать адаптивной, чтобы на мобилках выглядела корректно и сжималась.
Блог с хедером пришлось паддинги добавить по краям чтобы было как на макете ( но на мобилке плохо выглядит) - если паддинги убрать маленько разъезжается чуть дальше( я думаю из за того что инпут вправу увел способом марджин )

2024-02-19 12:47 UTC, GitEsense requested changes
В общем нужно пробежаться по комментариям, привести в порядок. Что же касается именования стилей хорошо бы, чтобы они были информативными, говорили за что за блок перед нами и "зачем", этого ранее не было, следующие занятия будут по методологиям, не плохо было бы ознакомиться и переименовать стили по БЭМ или SMACSS

По форме - доделать оформление (привести в соответствие с макетом) - отступы, заливки фонов, шрифты перепроверить и придерживаться принципа DRY

2024-02-19 12:47 UTC, GitEsense commented on 1-Blog/styleblog.css
> +    max-width: 1440px;
Я бы вот тут убрал максимальную ширину и запихнул в body

2024-02-19 12:47 UTC, GitEsense commented on 1-Blog/styleblog.css
> +
а как насчёт сделать gap: 39px; и padding: 0;
```
nav ul li:first-child {
   margin-right: 13px;
}
```
для nav задать margin-left: 77px;
это позволит сделать полное соответствие макету (1 -> 2 (52px) -> 3 (39px))

2024-02-19 12:47 UTC, GitEsense commented on 1-Blog/styleblog.css
>      margin: 0;
Как написано ниже - сделать max-width на body
margin: 0 auto; на body, чтобы позиционировать весь блок полность, тогда далее уже не будет нужды ограничивать layout (например в section можно будет убрать)

2024-02-19 12:47 UTC, GitEsense commented on 1-Blog/blog.html
> +                    </a>
Списки должны иметь структуру
```
ul
   li
   ...
   li
/ul
```
Если мы хотим сделать ссылками, то не li вкладываем в ссылку, а ссылку в li

2024-02-19 12:47 UTC, GitEsense commented on 1-Blog/styleblog.css
> +    padding-right: 180px;
Как тут, так и на logo не нужны такие внутренние отступы, нужно позиционироваться от layout, а у нас уже "прижимается к краю" за счёт margin-left: auto

2024-02-19 12:47 UTC, GitEsense commented on 1-Blog/styleblog.css
> +    padding-left: 180px;
аналогично инпута.
так же отсутствует отступ между иконкой и текстом, а по макету отступ 11px

2024-02-19 12:47 UTC, GitEsense commented on 1-Blog/blog.html
> +                </p>
А зачем у нас картинка в параграфе? если мы хотим обёртку, то тогда тут используем "div", но она тут не нужна, поэтому данную обёртку можно убрать и стили положить напрямую на изображение
p - это текстовый блок
div - это блок контента, картинка явно не текст)

2024-02-19 12:47 UTC, GitEsense commented on 1-Blog/blog.html
> +                    <p class="pimg1"><img src="./pimg1.png" alt="учитель курса">
Собственно аналогично, лишняя дополнительная обёртка

2024-02-19 12:47 UTC, GitEsense commented on 1-Blog/styleblog.css
> +/* загрузка */
:/

2024-02-19 12:47 UTC, GitEsense commented on 2-form/styleform.css
>      height: 44px;
Можно убрать ширину блока и добавить padding на все input с текстовым типом, например
```
input[type="text"]{
 padding: 9px 11px;
}
```
Это сделает блоки нужного размера и при изменении шрифта ничего никуда не поедет

2024-02-19 13:22 UTC, OlegGluhov commented on 2-form/styleform.css
>      height: 44px;
по поводу заливки шрифтов
тоесть отступы у плэйсхолдееров поставить?
и моя компания по другому залить и шрифт другой сделать ?  чтобы все в точности как на макете было?

2024-02-19 13:48 UTC, GitEsense commented on 2-form/styleform.css
>      height: 44px;
> по поводу заливки и шрифтов перепроверить тоесть отступы у плэйсхолдееров поставить? и "моя компания" инпут по другому залить и шрифт другой сделать ? чтобы все в точности как на макете было?

совершенно верно, только отступы не на placeholder, а на сам инпут
```
input {
    color: #999;
    background-color: #f5f5f5;
    font-size: 16px;
    font-style: italic;
    border: 0;
    border-radius: 5px;
    width: 100%;
    line-height: 26px;
    border: 1px solid #f5f5f5;
    padding: 9px 35px 9px 11px;
}
```
Как пример)

2024-02-19 13:51 UTC, GitEsense commented on 2-form/styleform.css
>      height: 44px;
для макета вполне пойдёт такой формат стиля:
```
input {
    color: #999;
    background-color: #f5f5f5;
    font-size: 16px;
    font-style: italic;
    border: 0;
    border-radius: 5px;
    width: 100%;
    line-height: 26px;
    border: 1px solid #f5f5f5;
    padding: 9px 35px 9px 11px;
}
```
```
input[name='company'] {
    background-color: #fff;
    color: #333;
    font-style: normal;
    font-weight: 600;
}
```
```
input[type="checkbox"] {
width: unset
}
```

А вот тут у нас field - это блок с Фамилия + Имя, а дальше отдельно им ставим бордеры
```
.field {
    display: flex;
    gap: 1px;
}
.field__firstname {
    border-radius: 5px 0 0 5px;
}
.field__surname {
    border-radius: 0 5px 5px 0;
}
```

Все инпуты будут одинаковы, не придётся стилизовать отдельно, все стили будут общими и лишь где надо изменить - просто применяем "после"

2024-02-20 11:01 UTC, OlegGluhov commented
Правки внес.
Стили переименовал по БЭМ - но я думаю не совсем корректно (болие полное понимание я думаю придем в теме "20. Проект - Вёрстка страницы школы")

2024-02-23 08:43 UTC, GitEsense approved these changes
Ну в принципе всё отлично, однако, на будущее лучше стараться максимально переиспользовать (придерживаться принципа DRY) и по БЭМ всё-таки попрактиковаться

2024-03-07 13:06 UTC, merged