Final
OlegGluhov/DZ2024 pull request #4
Opened 2024-03-07 13:13 UTC by OlegGluhov

2024-03-07 13:23 UTC, OlegGluhov commented
Добрый день)
ошибок скорее всего прилично((((
голову забил себе позицианированием (хотел реализовать некоторые формы с помощью CSS и при адаптиве травмировал психику ))) (поэтому возможны следы от сотни проб поведения ээлементов)

Формочку "Сокращайте расходы" сделал CSS но размеры задал в пикселях, при адаптиве произошли стращные вещи, решил сделать картинкой( сделал вывод что все надо делать в %, для дальнейшего адаптива)
Форму "Экономьте время и нервы на учете" - также пытался сделать CSS из 2х картинок, но почемуто при адаптиве эти 2 картинки синхронно не сжимались (получался перекос)(также с фигмы экспортируются не 2 одинаковые картинки а 1 маленькая другая большая, они там наложены друг на друга(также реализовывал это с помощью CSS и также не получается, идет рассинхрон сжатия) поэтому также решил сделать 1 картинкой

2024-03-11 18:48 UTC, GitEsense requested changes
В общем и  целом не плохо, но доработать надо
Что же по поводу блока "Экономия времени и ..."
Вот такая реализация как вариант:
```css
.comparison-image {
    position: relative;
    &::after {
        content: '';
        position: absolute;
        top: 0;
        left: 50%;
        transform: translateX(-50%);
        background: var(--color-text-primary);
        width: 2px;
        height: 100%;
        z-index: 3;
    }
    &::before {
        content: url('../images/icons/slider_icon.svg');
        cursor: pointer;
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        z-index: 4;
    }
}
.comparison-image__image {
    width: 100%;
    display: block;
    border-radius: 16px;
}
.comparison-image__before {
    z-index: 1;
}

.comparison-image__after {
    position: absolute;
    top: 0;
    left: 0;
    z-index: 2;
    width: 50%;
    overflow: hidden;
    .comparison-image__image {
        width: 200%;
    }
}
```
```html
<div class="comparison-image">
    <div class="comparison-image__after">
        <img class="comparison-image__image" src="./images/image-block_1.png" alt="" />
    </div>
    <div class="comparison-image__before">
        <img class="comparison-image__image" src="./images/image-block_2.png" alt="" />
    </div>
</div>
```

2024-03-11 18:48 UTC, GitEsense commented on 3-finio/styles/components.css
> +}
Сразу на доработку, по одной простой причине)
ступеньки
![image](https://github.com/OlegGluhov/DZ2024/assets/101252030/431a2440-405d-4e58-880d-2c54913627ca)

2024-03-11 18:48 UTC, GitEsense commented on 3-finio/styles/components.css
> +}
Необходимо соблюдать порядок каскада (появления классов, в том числе и по порядку подключения файлов), иначе мы получим такое поведение

![image](https://github.com/OlegGluhov/DZ2024/assets/101252030/60fb1656-b804-4e9b-b626-19d92e3201f9)

2024-03-11 18:48 UTC, GitEsense commented on 3-finio/styles/page.css
> +    gap: 16px;
Чтобы не ломать весь gap, можно указать gap: 16px 32px;
или дополнительно менять row-gap или column-gap в медиа выражениях

2024-03-11 18:48 UTC, GitEsense commented on 3-finio/finio.html
> +    <section class="section section-light_header">
не совсем так работает БЭМ)
можно было бы сделать например так

```html 
 <section class="section section__header_light">
```
или
```html
 <section class="section header__section section-light ">
```
и т.п.

2024-03-11 18:48 UTC, GitEsense commented on 3-finio/finio.html
> +    <section class="section_statistic">
Так это элемент или модификатор?)

2024-03-11 18:48 UTC, GitEsense commented on 3-finio/finio.html
> +            <div class="hero">
```
hero
   hero__wrapper
   hero__left
   hero__h1
   hero__logos
   hero__right
```
или
```
hero  hero__wrapper
   hero__left
   hero__h1
   hero__logos
   hero__right
```

2024-03-11 18:48 UTC, GitEsense commented on 3-finio/styles/global.css
> +}
А вот на body лучше указать минимальный размер layout , чтобы не "ужималось" в 0

2024-03-11 18:48 UTC, GitEsense commented on 3-finio/styles/components.css
> +}
рекомендую пересмотреть параметры и не забыть про шрифт, про перенос строки (вспоминаем про white-space), про padding, смещения и т.п.

Выставьте размер 375px и увидите страшное )
![image](https://github.com/OlegGluhov/DZ2024/assets/101252030/8f24c583-f92d-4ca4-bfc7-bad8582244d6)
вот так в макете

![image](https://github.com/OlegGluhov/DZ2024/assets/101252030/f6464a8a-a9ea-410b-b3ab-aec5afd49195)
а вот так на "выходе"

2024-03-17 18:57 UTC, GitEsense requested changes
![image](https://github.com/OlegGluhov/DZ2024/assets/101252030/c053f638-4663-45f9-a3e6-e9917d5ae4aa)

![image](https://github.com/OlegGluhov/DZ2024/assets/101252030/bc90ccd3-cd8c-420d-9cc5-2133845c90e4)
![image](https://github.com/OlegGluhov/DZ2024/assets/101252030/c99cae6e-7d1d-493b-8de0-f30190aac8ff)

Как мы видим - картинки разного размера, заливка не одинаковая, как и положение, а так же отступы , что же касается "отзывов", то и иконку напутали.

Давайте Вы пройдётесь по макету и проекту, перепроверите и глянем снова уже на "финальной" стадии

2024-03-18 13:49 UTC, OlegGluhov commented
Добрый день! ПО градиенту раза с 100 попал)
Что касается значка слайда, это просто когда делал форму "экономьте время" иконку без черты вертикальной назвал также (и естественно незаметил этого)
Пробежался по всему проекту - косяки которые еще нашол исправил!

2024-03-20 18:17 UTC, merged